name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: "0 0 * * *"

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout V
        uses: actions/checkout@v2
        with:
          repository: vlang/v
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          path: repo
      - name: Build V
        run: |
          make
          sudo ./v symlink
      - name: v fmt
        run: |
          cd repo
          v fmt -w .
          git diff --exit-code
      - name: v vet .
        run: |
          cd repo
          v vet .
      - name: v test .
        run: |
          cd repo
          v test .

